# Refer: https://medium.com/swlh/dockerize-your-python-command-line-program-6a273f5c5544

version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: mysecretpassword
